version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - uploads:/app/uploads
    networks:
      - smart-campus-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - smart-campus-net

volumes:
  uploads:

networks:
  smart-campus-net:
    driver: bridge
